"""Nerlex public Python API."""

from nerlex.calibration import (
    CalibratedPrediction,
    CalibrationError,
    TemperatureCalibrationArtifact,
    TemperatureCalibrationConfig,
    apply_temperature,
    calibrate_prediction,
    fit_temperature,
    load_calibration_artifact,
    predict_calibrated,
    write_calibration_artifact,
)
from nerlex.capture import CaptureRun, capture, observe_outcome
from nerlex.compiler import (
    CentroidCompiler,
    CentroidConfig,
    CompilerArtifact,
    CompilerError,
    CompilerPrediction,
    MultinomialNBCompiler,
    MultinomialNBConfig,
    compile_snapshot,
    load_compiler_artifact,
    predict,
    write_compiler_artifact,
)
from nerlex.dataset import (
    DatasetExample,
    DatasetSnapshot,
    DatasetSplit,
    SnapshotConfig,
    SnapshotManifest,
    SplitArtifact,
    SplitConfig,
    build_snapshot,
    verify_snapshot,
    write_snapshot,
)
from nerlex.evaluation import (
    EmpiricalRiskGateArtifact,
    EmpiricalRiskGateConfig,
    EvaluationConfig,
    EvaluationError,
    EvaluationReport,
    MetricSummary,
    RiskCoveragePoint,
    SelectiveSummary,
    evaluate,
    fit_empirical_risk_gate,
    load_evaluation_report,
    load_gate_artifact,
    write_evaluation_report,
    write_gate_artifact,
)
from nerlex.spec import (
    Candidate,
    CandidateMode,
    DecisionKind,
    DecisionRequest,
    DecisionResult,
    DecisionRoute,
    DecisionSpec,
    LabelObservation,
    LabelSource,
    validate_request,
)
from nerlex.store import SQLiteTraceStore
from nerlex.trace import ResultObservation, TraceRecord, export_jsonl, load_jsonl

__all__ = [
    "CalibratedPrediction",
    "CalibrationError",
    "Candidate",
    "CandidateMode",
    "CaptureRun",
    "CentroidCompiler",
    "CentroidConfig",
    "CompilerArtifact",
    "CompilerError",
    "CompilerPrediction",
    "DatasetExample",
    "DatasetSnapshot",
    "DatasetSplit",
    "EmpiricalRiskGateArtifact",
    "EmpiricalRiskGateConfig",
    "EvaluationConfig",
    "EvaluationError",
    "EvaluationReport",
    "DecisionKind",
    "DecisionRequest",
    "DecisionResult",
    "DecisionRoute",
    "DecisionSpec",
    "LabelObservation",
    "LabelSource",
    "MetricSummary",
    "MultinomialNBCompiler",
    "MultinomialNBConfig",
    "ResultObservation",
    "RiskCoveragePoint",
    "SQLiteTraceStore",
    "SelectiveSummary",
    "SnapshotConfig",
    "SnapshotManifest",
    "SplitArtifact",
    "SplitConfig",
    "TemperatureCalibrationArtifact",
    "TemperatureCalibrationConfig",
    "TraceRecord",
    "apply_temperature",
    "build_snapshot",
    "calibrate_prediction",
    "compile_snapshot",
    "capture",
    "evaluate",
    "export_jsonl",
    "fit_empirical_risk_gate",
    "fit_temperature",
    "load_calibration_artifact",
    "load_compiler_artifact",
    "load_evaluation_report",
    "load_gate_artifact",
    "load_jsonl",
    "observe_outcome",
    "predict",
    "predict_calibrated",
    "validate_request",
    "verify_snapshot",
    "write_calibration_artifact",
    "write_compiler_artifact",
    "write_evaluation_report",
    "write_gate_artifact",
    "write_snapshot",
]

__version__ = "0.1.0.dev0"
